config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'boards#index'
    
  resources :boards do
    resources :lists
  end
  resources :lists do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :first_name, :last_name, length:{ in: 2..20 }
  
  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def index
    @boards = current_user.boards
  end

  def show
    @board = current_user.boards.find(params[:id])
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def new
    @board = current_user.boards.new
  end

  def update
    @board = current_user.boards.find(params[:id]).update(board_params)
    if current_user.boards.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    current_user.boards.find(params[:id]).destroy
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :user_id)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_board
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = @board.cards
  end

  def show
  end
  
  def new
    @card = @board.cards.new
  end

  def create
    @card = @board.cards.new(card_params)

    if @board.cards.save
      redirect_to [@board, @card]
    else
      render :new
    end
  end

  def update
    if @board.cards.update(card_params)
      redirect_to [@board, @card]
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @board.destroy
    redirect_to [@board, @card]
  end

  private

  def set_board
    @board = current_user.boards.find(params[:board_id])
  end

  def set_card
    @card = @board.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :board_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end


  def edit
  end


  def create
    @item = Item.new(item_params)
      if @item.save
        redirect_to Board.find(Card.find(@item.card_id).board_id), notice: 'Item was successfully created.'
      else
        render :new
      end
  end


  def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.' 
      else
        render :edit
      end
  end
  


  def destroy
    @board = Board.find(Card.find(@item.card_id).board_id)
    @item.destroy
    redirect_to @board, notice: 'Item was successfully destroyed.' 
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :card_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @list = @board.lists
  end

  def show
  end

  def edit
 #   render :index
  end

  def update
    if @list.update(list_params)
      redirect_to [@board, @list]
    else
      render :edit
    end
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to [@board, @list]
    else
      render :new
    end
  end

  def new
    @list = @board.lists.new
  end

  def destroy
    @list.destroy
    redirect_to @index
  end

  private
  def set_board
    @board = current_user.boards.find(params[:board_id])
  end

  def set_list
    @list = @board.lists.find(params[:id])
  end
  
  def list_params
    params.require(:list).permit(:name, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h1>My Boards</h1>

<ul>
  <% @boards.each do |board| %>
  <li>
    <%= link_to board.name, board_path(board) %>
    <% end %>
  </li>
</ul>

<%= link_to 'Add New Board', new_board_path %>
<%= link_to 'Edit Board'%>
 <%= link_to 'Delete Board', @board, method: :delete %>

app/views/boards/new.html.erb
<h1>Add a New Board</h1>


<%= form_with(model: @board, local: true) do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
</div>
<br>
<%= f.submit %>

<% end %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>

<div class="">
  <div class=" ">
    <div class="">
      <div class=" ">
      </div>
    </div>
    <% @board.lists.each do |list| %>
        <div class="" style="height: 150px; margin: 5px; padding: 5px; border: 1px solid black; width: 40%;">
        <div class="placeholder">
            <div class="header">
                <p style="float: left;"><%= list.name %></p>
                
                <p style="float: right;"><%= link_to 'Add Item', new_item_path(list_id: list.id) %></p>
            </div>
            <br><br>
            <div>
              <% list.items.each do |item|%>     
                    <div style="float: left;"><%= item.name %></div>     
                    <div style="float: right;">
                    <%= link_to 'Edit', edit_item_path(list_id: list.id) %>
                    <%= link_to 'Delete', item, method: :delete %>
                    </div>
                    <br>
                <% end %>
            </div>
        </div>
        </div>
    <%end%>
  </div>
</div>


 

 <%= link_to 'Add List', new_board_list_path(board_id: @board.id) %>
 <%= link_to 'Delete Board', @board, method: :delete %>

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/index.html.erb
<div class="ui three doubling stackable cards">
  <div class="ui card">
    <div class="image">
      <div class="ui placeholder">
      </div>
    </div>
    <% @cards.each do |card| %>
        <div class="content">
        <div class="ui placeholder">
            <div class="header">
                <p><%= card.name %></p>
            </div>
            <div class="paragraph">
            <%= card.lists.each do |item|%>
                <ul>
                  <li><%= item.name %></li>
                </ul>
<%end%>
            </div>
        </div>
        </div>
    <%end%>
  </div>
</div>

app/views/cards/new.html.erb
<h1>Add a New Card</h1>


<%= form_with(model: @card, local: true) do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
</div>
<br>
<%= f.submit %>

<% end %>

app/views/cards/show.html.erb
<div class="ui three doubling stackable cards">
  <div class="ui card">
    <div class="image">
      <div class="ui placeholder">
      </div>
    </div>
    <% @cards.each do |card| %>
        <div class="content">
        <div class="ui placeholder">
            <div class="header">
                <p><%= card.name %></p>
            </div>
            <div class="paragraph">
            <%= card.lists.each do |item|%>
                <ul>
                  <li><%= item.name %></li>
                </ul>
<%end%>
            </div>
        </div>
        </div>
    <%end%>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.hidden_field :card_id, {value: params[:card_id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.card %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card:</strong>
  <%= @item.card %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clonetrello2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Add a New List</h1>


<%= form_with(model: @list, local: true) do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
</div>
<br>
<%= f.submit %>

<% end %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>